// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rl_environment_data.proto

package protos;

public final class RlEnvironmentData {
  private RlEnvironmentData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EnvironmentDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EnvironmentData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 state = 1;</code>
     */
    java.util.List<java.lang.Integer> getStateList();
    /**
     * <code>repeated int32 state = 1;</code>
     */
    int getStateCount();
    /**
     * <code>repeated int32 state = 1;</code>
     */
    int getState(int index);

    /**
     * <code>float lastActionReward = 2;</code>
     */
    float getLastActionReward();
  }
  /**
   * <pre>
   * The request message, tells the agent the current environment state
   * And the last reward for their last action
   * </pre>
   *
   * Protobuf type {@code EnvironmentData}
   */
  public  static final class EnvironmentData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EnvironmentData)
      EnvironmentDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnvironmentData.newBuilder() to construct.
    private EnvironmentData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnvironmentData() {
      state_ = java.util.Collections.emptyList();
      lastActionReward_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnvironmentData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                state_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              state_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                state_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                state_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 21: {

              lastActionReward_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          state_ = java.util.Collections.unmodifiableList(state_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.RlEnvironmentData.internal_static_EnvironmentData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.RlEnvironmentData.internal_static_EnvironmentData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.RlEnvironmentData.EnvironmentData.class, protos.RlEnvironmentData.EnvironmentData.Builder.class);
    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> state_;
    /**
     * <code>repeated int32 state = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getStateList() {
      return state_;
    }
    /**
     * <code>repeated int32 state = 1;</code>
     */
    public int getStateCount() {
      return state_.size();
    }
    /**
     * <code>repeated int32 state = 1;</code>
     */
    public int getState(int index) {
      return state_.get(index);
    }
    private int stateMemoizedSerializedSize = -1;

    public static final int LASTACTIONREWARD_FIELD_NUMBER = 2;
    private float lastActionReward_;
    /**
     * <code>float lastActionReward = 2;</code>
     */
    public float getLastActionReward() {
      return lastActionReward_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getStateList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(stateMemoizedSerializedSize);
      }
      for (int i = 0; i < state_.size(); i++) {
        output.writeInt32NoTag(state_.get(i));
      }
      if (lastActionReward_ != 0F) {
        output.writeFloat(2, lastActionReward_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < state_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(state_.get(i));
        }
        size += dataSize;
        if (!getStateList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        stateMemoizedSerializedSize = dataSize;
      }
      if (lastActionReward_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, lastActionReward_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.RlEnvironmentData.EnvironmentData)) {
        return super.equals(obj);
      }
      protos.RlEnvironmentData.EnvironmentData other = (protos.RlEnvironmentData.EnvironmentData) obj;

      boolean result = true;
      result = result && getStateList()
          .equals(other.getStateList());
      result = result && (
          java.lang.Float.floatToIntBits(getLastActionReward())
          == java.lang.Float.floatToIntBits(
              other.getLastActionReward()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStateCount() > 0) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getStateList().hashCode();
      }
      hash = (37 * hash) + LASTACTIONREWARD_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLastActionReward());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.RlEnvironmentData.EnvironmentData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.RlEnvironmentData.EnvironmentData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.RlEnvironmentData.EnvironmentData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message, tells the agent the current environment state
     * And the last reward for their last action
     * </pre>
     *
     * Protobuf type {@code EnvironmentData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EnvironmentData)
        protos.RlEnvironmentData.EnvironmentDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.RlEnvironmentData.internal_static_EnvironmentData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.RlEnvironmentData.internal_static_EnvironmentData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.RlEnvironmentData.EnvironmentData.class, protos.RlEnvironmentData.EnvironmentData.Builder.class);
      }

      // Construct using protos.RlEnvironmentData.EnvironmentData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        state_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        lastActionReward_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.RlEnvironmentData.internal_static_EnvironmentData_descriptor;
      }

      @java.lang.Override
      public protos.RlEnvironmentData.EnvironmentData getDefaultInstanceForType() {
        return protos.RlEnvironmentData.EnvironmentData.getDefaultInstance();
      }

      @java.lang.Override
      public protos.RlEnvironmentData.EnvironmentData build() {
        protos.RlEnvironmentData.EnvironmentData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.RlEnvironmentData.EnvironmentData buildPartial() {
        protos.RlEnvironmentData.EnvironmentData result = new protos.RlEnvironmentData.EnvironmentData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          state_ = java.util.Collections.unmodifiableList(state_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.state_ = state_;
        result.lastActionReward_ = lastActionReward_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.RlEnvironmentData.EnvironmentData) {
          return mergeFrom((protos.RlEnvironmentData.EnvironmentData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.RlEnvironmentData.EnvironmentData other) {
        if (other == protos.RlEnvironmentData.EnvironmentData.getDefaultInstance()) return this;
        if (!other.state_.isEmpty()) {
          if (state_.isEmpty()) {
            state_ = other.state_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStateIsMutable();
            state_.addAll(other.state_);
          }
          onChanged();
        }
        if (other.getLastActionReward() != 0F) {
          setLastActionReward(other.getLastActionReward());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.RlEnvironmentData.EnvironmentData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.RlEnvironmentData.EnvironmentData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> state_ = java.util.Collections.emptyList();
      private void ensureStateIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          state_ = new java.util.ArrayList<java.lang.Integer>(state_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 state = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getStateList() {
        return java.util.Collections.unmodifiableList(state_);
      }
      /**
       * <code>repeated int32 state = 1;</code>
       */
      public int getStateCount() {
        return state_.size();
      }
      /**
       * <code>repeated int32 state = 1;</code>
       */
      public int getState(int index) {
        return state_.get(index);
      }
      /**
       * <code>repeated int32 state = 1;</code>
       */
      public Builder setState(
          int index, int value) {
        ensureStateIsMutable();
        state_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 state = 1;</code>
       */
      public Builder addState(int value) {
        ensureStateIsMutable();
        state_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 state = 1;</code>
       */
      public Builder addAllState(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureStateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, state_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 state = 1;</code>
       */
      public Builder clearState() {
        state_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private float lastActionReward_ ;
      /**
       * <code>float lastActionReward = 2;</code>
       */
      public float getLastActionReward() {
        return lastActionReward_;
      }
      /**
       * <code>float lastActionReward = 2;</code>
       */
      public Builder setLastActionReward(float value) {
        
        lastActionReward_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float lastActionReward = 2;</code>
       */
      public Builder clearLastActionReward() {
        
        lastActionReward_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EnvironmentData)
    }

    // @@protoc_insertion_point(class_scope:EnvironmentData)
    private static final protos.RlEnvironmentData.EnvironmentData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.RlEnvironmentData.EnvironmentData();
    }

    public static protos.RlEnvironmentData.EnvironmentData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnvironmentData>
        PARSER = new com.google.protobuf.AbstractParser<EnvironmentData>() {
      @java.lang.Override
      public EnvironmentData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnvironmentData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnvironmentData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnvironmentData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.RlEnvironmentData.EnvironmentData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActionResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActionResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 action = 1;</code>
     */
    int getAction();
  }
  /**
   * <pre>
   * The response message, what action the agent wants to preform
   * </pre>
   *
   * Protobuf type {@code ActionResponse}
   */
  public  static final class ActionResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ActionResponse)
      ActionResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActionResponse.newBuilder() to construct.
    private ActionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActionResponse() {
      action_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActionResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              action_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protos.RlEnvironmentData.internal_static_ActionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protos.RlEnvironmentData.internal_static_ActionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protos.RlEnvironmentData.ActionResponse.class, protos.RlEnvironmentData.ActionResponse.Builder.class);
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private int action_;
    /**
     * <code>int32 action = 1;</code>
     */
    public int getAction() {
      return action_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (action_ != 0) {
        output.writeInt32(1, action_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (action_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, action_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protos.RlEnvironmentData.ActionResponse)) {
        return super.equals(obj);
      }
      protos.RlEnvironmentData.ActionResponse other = (protos.RlEnvironmentData.ActionResponse) obj;

      boolean result = true;
      result = result && (getAction()
          == other.getAction());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protos.RlEnvironmentData.ActionResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.RlEnvironmentData.ActionResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.RlEnvironmentData.ActionResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.RlEnvironmentData.ActionResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.RlEnvironmentData.ActionResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protos.RlEnvironmentData.ActionResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protos.RlEnvironmentData.ActionResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.RlEnvironmentData.ActionResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.RlEnvironmentData.ActionResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protos.RlEnvironmentData.ActionResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protos.RlEnvironmentData.ActionResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protos.RlEnvironmentData.ActionResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protos.RlEnvironmentData.ActionResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message, what action the agent wants to preform
     * </pre>
     *
     * Protobuf type {@code ActionResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ActionResponse)
        protos.RlEnvironmentData.ActionResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protos.RlEnvironmentData.internal_static_ActionResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protos.RlEnvironmentData.internal_static_ActionResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protos.RlEnvironmentData.ActionResponse.class, protos.RlEnvironmentData.ActionResponse.Builder.class);
      }

      // Construct using protos.RlEnvironmentData.ActionResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        action_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protos.RlEnvironmentData.internal_static_ActionResponse_descriptor;
      }

      @java.lang.Override
      public protos.RlEnvironmentData.ActionResponse getDefaultInstanceForType() {
        return protos.RlEnvironmentData.ActionResponse.getDefaultInstance();
      }

      @java.lang.Override
      public protos.RlEnvironmentData.ActionResponse build() {
        protos.RlEnvironmentData.ActionResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protos.RlEnvironmentData.ActionResponse buildPartial() {
        protos.RlEnvironmentData.ActionResponse result = new protos.RlEnvironmentData.ActionResponse(this);
        result.action_ = action_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protos.RlEnvironmentData.ActionResponse) {
          return mergeFrom((protos.RlEnvironmentData.ActionResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protos.RlEnvironmentData.ActionResponse other) {
        if (other == protos.RlEnvironmentData.ActionResponse.getDefaultInstance()) return this;
        if (other.getAction() != 0) {
          setAction(other.getAction());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protos.RlEnvironmentData.ActionResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protos.RlEnvironmentData.ActionResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int action_ ;
      /**
       * <code>int32 action = 1;</code>
       */
      public int getAction() {
        return action_;
      }
      /**
       * <code>int32 action = 1;</code>
       */
      public Builder setAction(int value) {
        
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 action = 1;</code>
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ActionResponse)
    }

    // @@protoc_insertion_point(class_scope:ActionResponse)
    private static final protos.RlEnvironmentData.ActionResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protos.RlEnvironmentData.ActionResponse();
    }

    public static protos.RlEnvironmentData.ActionResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActionResponse>
        PARSER = new com.google.protobuf.AbstractParser<ActionResponse>() {
      @java.lang.Override
      public ActionResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActionResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActionResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActionResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protos.RlEnvironmentData.ActionResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnvironmentData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnvironmentData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActionResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031rl_environment_data.proto\":\n\017Environme" +
      "ntData\022\r\n\005state\030\001 \003(\005\022\030\n\020lastActionRewar" +
      "d\030\002 \001(\002\" \n\016ActionResponse\022\016\n\006action\030\001 \001(" +
      "\0052L\n\022EnvironmentService\0226\n\017SendEnvironme" +
      "nt\022\020.EnvironmentData\032\017.ActionResponse\"\000B" +
      "\010\n\006protosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnvironmentData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnvironmentData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnvironmentData_descriptor,
        new java.lang.String[] { "State", "LastActionReward", });
    internal_static_ActionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ActionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActionResponse_descriptor,
        new java.lang.String[] { "Action", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
